listings/urls.py
from django.conf.urls import patterns, url
from listings import views

# This is declaring the URL for my browse view
urlpatterns = [
    url(r'^browse', views.browse, name='browse'),
    url(r'^(?P<pk>[0-9]+)/listing/', views.listing, name='listing'),

]

main/urls.py
from django.conf.urls import patterns, url
import main.views

# These are my URL's for the index, about and 404 page
urlpatterns = [
    url(r'^$', main.views.index, name='index'),
    url(r'^about/$', main.views.about, name="about"),
    url(r'^credits/$', main.views.credits, name="credits"),
    url(r'^sorry/$', main.views.featurenotimplemented, name="featurenotimplemented"),
    url(r'^permission_denied/$', main.views.permissiondenied, name="permissiondenied"),

]

opus_jobs_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import django.contrib.auth.views

urlpatterns = [

    url(r'^admin/', include(admin.site.urls), name='admin'),
    url(r'^', include('main.urls')),
    url(r'^profiles/', include('profiles.urls')),
    url(r'^listings/', include('listings.urls')),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, {'next_page': '/'}),
    url(r'^accounts/', include('allauth.urls')),

]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

#This is the model for my extended signup profile
class SignUpProfile(models.Model):
    account_type_choice = (
        ('1', 'Student'),
        ('2', 'Employer')
    )

    user = models.OneToOneField(User, unique=True)
    account_type = models.CharField(max_length=10, choices=account_type_choice)
    contact_number = models.IntegerField()

    class Meta:
        verbose_name = 'SignUp Profile'

    def __unicode__(self):
        return "%s" % self.user

# This is the model for my edit and add job listing page
class JobListing(models.Model):

    region_choice = (
        ('1', 'Auckland'),
        ('2', 'Wellington'),
        ('3', 'Christchurch')
    )
    suburb_choice = (
        ('1', 'Glendowie'),
        ('2', 'Kohimarama'),
        ('3', 'Herne Bay')
    )
    industry_choice = (
        ('1', 'Accounting'),
        ('2', 'Agriculture, fishing & forestry'),
        ('3', 'Automotive'),
        ('4', 'Banking, finance & insurance'),
        ('5', 'Construction & Architecture'),
        ('6', 'Customer service'),
    )
    employment_type_choice = (
        ('1', 'Full Time'),
        ('2', 'Part Time'),
        ('3', 'One-off'),
        ('4', 'Other')
    )
    area_code_choice = (
        ('1', '021'),
        ('2', '027'),
        ('3', '022'),
        ('4', '09')
    )

    user = models.CharField(max_length=50)
    job_title = models.CharField(max_length=30)
    pay_rate = models.DecimalField(max_digits=10, decimal_places=2)
    employment_type = models.CharField(max_length=10, choices=employment_type_choice)
    job_description = models.CharField(max_length=2000)
    business_address_region = models.CharField(max_length=50, choices=region_choice)
    business_address_suburb = models.CharField(max_length=50, choices=suburb_choice)
    business_industry = models.CharField(max_length=50, choices=industry_choice)
    email = models.EmailField(max_length=50, blank=True, null=True)
    telephone = models.CharField(max_length=20, blank=True, null=True)
    area_code = models.CharField(max_length=5, choices=area_code_choice, blank=True)
    listing_view_counter = models.IntegerField(default=0)
    active_listing = models.BooleanField(default=True)
    listing_date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Job Listing'

    def clean(self):
        if not (self.email or self.telephone):
            raise ValidationError("You must specify either email or telephone")
        if not self.email:
            self.email = ""
        if not self.telephone:
            self.telephone = ""

    def __unicode__(self):
        return "%s" % self.job_title

listings/forms.py
from django import forms

region_choice = (
    ('', 'Region'),
    ('1', 'Auckland'),
    ('2', 'Wellington'),
    ('3', 'Christchurch')
)
suburb_choice = (
    ('', 'None'),
    ('1', 'Glendowie'),
    ('2', 'Kohimarama'),
    ('3', 'Herne Bay')
)
industry_choice = (
    ('', 'Business Industry'),
    ('1', 'Accounting'),
    ('2', 'Agriculture, fishing & forestry'),
    ('3', 'Automotive'),
    ('4', 'Banking, finance & insurance'),
    ('5', 'Construction & Architecture'),
    ('6', 'Customer service'),
)
employment_type_choice = (
    ('', 'Employment Type'),
    ('1', 'Full Time'),
    ('2', 'Part Time'),
    ('3', 'One-off'),
    ('4', 'Other')
)

class JobQuickSearchForm(forms.Form):
    business_address_region = forms.ChoiceField(region_choice, widget=forms.Select(attrs={'class': 'qs-form-input'}))
    business_industry = forms.ChoiceField(industry_choice, widget=forms.Select(attrs={'class': 'qs-form-input'}))
    keywords = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'qs-form-input', 'placeholder': 'Enter Keywords...'}))

class JobSearchForm(forms.Form):
    employment_type = forms.ChoiceField(employment_type_choice, widget=forms.Select(attrs={'class': 'qsm-form-input'}))
    business_address_region = forms.ChoiceField(region_choice, widget=forms.Select(attrs={'class': 'qsm-form-input'}))
    business_industry = forms.ChoiceField(industry_choice, widget=forms.Select(attrs={'class': 'qsm-form-input'}))
    keywords = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'qsm-form-input', 'placeholder': 'Enter Keywords...'}))

listings/views.py
from django.shortcuts import render
from profiles.models import JobListing
from forms import JobSearchForm
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# This is the view function for displaying the browse page
def browse(request):

    business_industry = request.GET.get('business_industry', '')
    business_address_region = request.GET.get('business_address_region', '')
    employment_type = request.GET.get('employment_type', '')
    pay_rate = request.GET.get('pay_rate', '')
    keywords = request.GET.get('keywords', '').split()

    form = JobSearchForm(initial=request.GET)

    filters = Q(active_listing=True)

    if business_industry:
        filters &= Q(business_industry=business_industry)
    if business_address_region:
        filters &= Q(business_address_region=business_address_region)
    if employment_type:
        filters &= Q(employment_type=employment_type)
    if pay_rate:
        filters &= Q(pay_rate=pay_rate)
    if keywords:
        filters &= reduce(lambda x, y: x & y, [Q(job_description__icontains=word) for word in keywords]) | reduce(lambda x, y: x & y, [Q(job_title__icontains=word) for word in keywords])

    job_listings_list = JobListing.objects.filter(filters).distinct().order_by('-listing_date')

    paginator = Paginator(job_listings_list, 3) # Show 25 contacts per page

    page = request.GET.get('page')

    try:
        job_listings = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        job_listings = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        job_listings = paginator.page(paginator.num_pages)

    current_page_start = job_listings.start_index()
    current_page_end = job_listings.end_index()

    before_current_pages = 4
    after_current_pages = 4
    before = max(job_listings.number - before_current_pages - 1, 0)
    after = job_listings.number + after_current_pages
    page_range = list(job_listings.paginator.page_range)
    middle = page_range[before:after]

    queries_without_page = request.GET.copy()
    if 'page' in queries_without_page:
        del queries_without_page['page']

    context_dict = {
        'joblistings': job_listings,
        'job_listings_list': job_listings_list,
        'current_page_start': current_page_start,
        'current_page_end': current_page_end,
        'form': form,
        'middle': middle,
        'queries': queries_without_page,
    }

    return render(request, 'browse.html', context_dict)

def listing(request, pk,):

    job_listing = JobListing.objects.get(pk=pk)

    def view_counter():
        view_count = job_listing.listing_view_counter
        job_listing.listing_view_counter = view_count + 1
        job_listing.save()
        print(view_count)

    view_counter()

    context_dict = {'joblistings': job_listing}

    return render(request, 'listing.html', context_dict)

templates/about.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="about-divider">
        <h1>The Foundations</h1>
    </div>
        <div class="about-section-1">
            <table>
                <tr>
                    <td>
                        <p class="about-1">Formulated in late 2010, our teams vision has always been a student oriented website, built on the principles of connecting student to employer in the most convenient and functional way possible. Now 5 years in the making we are proud to bring you Opus Jobs,</p>
                    </td>
                    <td>
                        <p class="about-2">the leading website in student employee relations.  We believe that age is but a number and those with the diligence to search for work should not be disadvantaged by a lack of job finding mediums. As for employees, students are a readily available</p>
                    </td>
                    <td>
                        <p class="about-2">and hardworking resource that can be both equitable and efficient for the future of your business. Our sites convenience and ease of use has brought numerous satisfied employees and employers together, forming long lasting job opportunities, will you be next?</p>
                    </td>
                </tr>
            </table>
        </div>
    <div class="about-divider">
        <h1>How it Works</h1>
    </div>
    <div id="information">
        <div class="information-div">
            <a href="{% url "account_signup" %}"><img src="{% static 'images/icon1.png' %}" ></img></a>
            <p>Register an Account</p>
        </div>
        <div class="information-div">
            <a href="{% url "browse" %}"><img src="{% static 'images/icon2.png' %}" ></img></a>
            <p>Browse Job Listings</p>
        </div>
        <div class="information-div">
            <a href="{% url "browse" %}"><img src="{% static 'images/icon3.png' %}" ></img></a>
            <p>Contact The Employer</p>
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
    <!-- Designed by eZ_Harry  -->
    <meta charset="UTF-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link rel="icon" href="{% static 'images/ico.ico' %}" type="image/x-icon"/>
	<title>Opus Jobs</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>
        <div id="header">
        <ul style="margin-top: 0px; padding-left: 0px;">
          <a href="{% url 'index' %}"><img src="{% static 'images/logo2.png' %}" id="logo"/></a>
          {% if user.is_active %} <!-- This checks the user is active and then grabs their username to put in the nav bar  -->
              <li class="link"><a href="{% url 'account_logout' %}">Logout. ({{ user.get_username }})</a></li>
              {% if user.signupprofile.account_type == '2' %} <!-- This selects which dropdown menu to display based on the users account type -->
              <li class="link-drop"><a>My Account</a>
                <ul class="link-drop-ul">
                    <div class="triangle"></div>
                    <div class="link-drop-box">
                    <li><a class="link-drop-a" href="{% url 'account_change_password' %}">Edit Profile</a></li>
                    <li><a class="link-drop-a" href="{% url 'editlistingportal' %}">Edit Listings</a></li>
                    <li><a class="link-drop-a" href="{% url 'account_logout' %}">Logout</a></li>
                    </div>
                </ul>
              </li>
              {% else %}
              <li class="link-drop"><a>My Account</a>
                <ul class="link-drop-ul">
                    <div class="triangle"></div>
                    <div class="link-drop-box">
                    <li><a href="{% url 'account_change_password' %}">Edit Profile</a></li>
                    <li><a href="{% url 'account_logout' %}">Logout</a></li>
                    </div>
                </ul>
              </li>
              {% endif %}


          {% else %}
              <li class="link"><a href="{% url 'account_login' %}">Login.</a></li> <!-- The URL function in here is what Django uses to link pages  -->
              <li class="link"><a href="{% url 'account_signup' %}">Register</a></li>

          {% endif %}
              <li class="link"><a href="{% url 'about' %}">About</a></li>
              <li class="link-drop"><a>Employer</a>
                  <ul class="link-drop-ul">
                      <div class="triangle"></div>
                      <div class="link-drop-box">
                          <li><a class="link-drop-a" href="{% url 'createjoblisting' %}">Add Listing</a></li>
                           <!-- <li><a class="link-drop-a" href="{% url 'featurenotimplemented' %}">How it works</a></li> To be added later -->
                      </div>
                  </ul>
              </li>
              <li class="link-drop"><a>Student</a>
                  <ul class="link-drop-ul">
                      <div class="triangle"></div>
                      <div class="link-drop-box">
                          <li><a class="link-drop-a" href="{% url 'browse' %}">Job Listings</a></li>
                          <!-- <li><a class="link-drop-a" href="{% url 'featurenotimplemented' %}">How it works</a></li> To be added later -->
                      </div>
                  </ul>
              </li>
              <li class="link"><a href="{% url 'index' %}">Home</a></li>
        </ul>
        </div>

        <div id="content">
        {% block content %} <!-- This is used to extend the base.html file to other html pages -->
        {% endblock %}
        </div>

        <div id="footer"> <!-- This is the websites footer bar  -->
            <hr>
            <div>
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'featurenotimplemented' %}">Contact</a></li>
                <li><a href="{% url 'credits' %}">Credits</a></li>
                <li><a href="{% url 'account_login' %}">Login</a></li>
            </div>
        </div>
</body>
</html>

templates/browse.html
{% extends "base.html" %}

{% block content %}
    <h1 class="pageheader">Current Job Listings</h1>
    <div class="browser-aligner">
    <div class="browser-wrapper">
    <p class="jobcounter">Showing <b>{{ current_page_start }}</b> to <b>{{ current_page_end }}</b> of <b>{{ job_listings_list.count }}</b> jobs available</p>
        <div class="searchrefiner">
            <h2 class="searchrefiner-title">Job Finder</h2>
            <form class="qsm-form" action="{% url 'browse' %}">
                {{ form.non_field_errors }}
                <p class="searchrefiner-field-title">Business Industry</p><br>
                {{ form.business_industry }}
                <p class="searchrefiner-field-title">Business Region</p><br>
                {{ form.business_address_region }}
                <p class="searchrefiner-field-title">Employment Type</p><br>
                {{ form.employment_type }}
                <p class="searchrefiner-field-title">Keywords</p><br>
                {{ form.keywords }}<br>
                <button type="submit" class="qsm-form-button">Search Jobs</button>
            </form>
            <div><a href="{% url "browse" %}">Clear Search Results</a></div>
        </div>
        <div class="joblistings">
        {% if joblistings %} <!-- This is the for loop used to display the job listings content  -->
                {% for joblisting in joblistings %}
                     <div class="listings-item">
                       <a href="{% url 'listing' joblisting.pk %}">
                       <ul>
                       <li class="listing-title">{{ joblisting.job_title|capfirst }}</li>
                       <li>Region: {{ joblisting.get_business_address_suburb_display|capfirst }}</li>
                       <li>Pay Rate: ${{ joblisting.pay_rate }}</li>
                       <li>Listing Date: {{ joblisting.listing_date }}</li>
                       </ul>
                       </a>
                     </div>
                {% endfor %}

        {% else %}
            <p>Unfortunately all of the job opportunities have been taken at this moment.</p>
        {% endif %}
        </div>
    </div>
    </div>
    <div class="pagination">
     <ul>
        {% if joblistings.has_previous %}
            <li><a href="?{{queries.urlencode}}&amp;page={{ joblistings.previous_page_number }}">Prev</a></li>
        {% endif %}

        {% if joblistings.paginator.num_pages > 1 %}
            {% if middle %}
                {% for pnum in middle %}
                    <a href="?{{queries.urlencode}}&amp;page={{ pnum }}"{% if joblistings.number == pnum %} style="font-weight: bold"{% endif %}>{{ pnum }}</a>
                {% endfor %}
            {% endif %}
        {% endif %}

        {% if joblistings.has_next %}
            <li><a href="?{{queries.urlencode}}&amp;page={{ joblistings.next_page_number }}">Next</a></li>
        {% endif %}
     </ul>
    </div>

    <script type="text/javascript">
    // This function removes empty GET parameters
        jQuery(document).ready(function($){

            $(".qsm-form").submit(function() {
                $(this).find(":input").filter(function(){ return !this.value; }).attr("disabled", "disabled");
                return true; // ensure form still submits
            });

            // Un-disable form fields when page loads, in case they click back after submission
            $( ".qsm-form" ).find( ":input" ).prop( "disabled", false );

        })
    </script>

{% endblock %}

templates/createjoblisting.html
{% extends "base.html" %}

{% block content %}
<div id="createjoblisting">
    <h1 class="pageheader">Create a Job Listing</h1>
    <form class="createjoblisting" id="createjoblisting_form" method="post" action="{% url 'createjoblisting' %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <p> <label for="id_username" class="form-input-label">Job Title</label><br>
        {{ form.job_title }}<br><p>{{ form.job_title.errors }}
        <p><label for="id_username" class="form-input-label">Pay Rate</label><br>
        {{ form.pay_rate }}<br><p>{{ form.pay_rate.errors }}
        <p><label for="id_username" class="form-input-label">Employment Type</label><br>
        {{ form.employment_type }}<br><p>{{ form.employment_type.errors }}
        <p><label for="id_username" class="form-input-label">Job Description</label><br>
        {{ form.job_description }}<br><p>{{ form.job_description.errors }}
        <p><label for="id_username" class="form-input-label">Business Region</label><br>
        {{ form.business_address_region }}<br><p>{{ form.business_address_region.errors }}
        <p><label for="id_username" class="form-input-label">Business Suburb</label><br>
        {{ form.business_address_suburb }}<br><p>{{ form.business_address_suburb.errors }}
        <p><label for="id_username" class="form-input-label">Business Industry</label><br>
        {{ form.business_industry }}<br><p>{{ form.business_industry.errors }}
        <p><label for="id_username" class="form-input-label">Email <i class="form-optional-tag">(Optional)</i></label><br>
        {{ form.email }}<br><p>{{ form.email.errors }}
        <p class="form-contact-split"><label for="id_username" class="form-input-label">Contact Number <i class="form-optional-tag">(Optional)</i></label><br>
        {{ form.area_code }}{{ form.telephone }}<br><p>{{ form.telephone.errors }}{{ form.area_code.errors }}
        <button type="submit" class="form-button">Create Job Listing</button>
    </form>
</div>
{% endblock %}

templates/credits.html
{% extends "base.html" %}

{% block content %}

    <h1 class="creditsheader">Credits:</h1>
    <ul class="creditslinks">
        <li>http://www.danilodemarco.com/ - Desktop Icon - Index Page</li>
        <li>http://designrockr.com/ - Folder Icon - Index Page</li>
        <li>http://linhpham.me/ - Letter Icon - Index Page</li>
    </ul>

{% endblock %}

templates/delete_listing_confirm.html
{% extends "base.html" %}

{% block content %}
    <h1 class="pageheader">Delete your listing?</h1>
<div class="delete-listing">
    <div><a href="{% url 'deletefunction' post.pk %}">Yes, I'd like to delete my listing</a><br></div>
    <div><a href="{% url 'editlistingportal' %}">Cancel</a></div>
</div>
{% endblock %}

templates/editlisting.html
{% extends "base.html" %}

{% block content %}
<div id="createjoblisting">
    <h1 class="pageheader">Edit Your Job Listing</h1>
    <form class="createjoblisting" id="createjoblisting_form" method="post" action="{% url 'editlisting' post.pk %}">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <p> <label for="id_username" class="form-input-label">Job Title</label><br>
        {{ form.job_title }}<br><p>{{ form.job_title.errors }}
        <p><label for="id_username" class="form-input-label">Pay Rate</label><br>
        {{ form.pay_rate }}<br></p>{{ form.pay_rate.errors }}
        <p><label for="id_username" class="form-input-label">Employment Type</label><br>
        {{ form.employment_type }}<br><p>{{ form.employment_type.errors }}
        <p><label for="id_username" class="form-input-label">Job Description</label><br>
        {{ form.job_description }}<br><p>{{ form.job_description.errors }}
        <p><label for="id_username" class="form-input-label">Business Region</label><br>
        {{ form.business_address_region }}<br><p>{{ form.business_address_region.errors }}
        <p><label for="id_username" class="form-input-label">Business Suburb</label><br>
        {{ form.business_address_suburb }}<br><p>{{ form.business_address_suburb.errors }}
        <p><label for="id_username" class="form-input-label">Business Industry</label><br>
        {{ form.business_industry }}<br><p>{{ form.business_industry.errors }}
        <p><label for="id_username" class="form-input-label">Email <i class="form-optional-tag">(Optional)</i></label><br>
        {{ form.email }}<br><p>{{ form.email.errors }}
        <p class="form-contact-split"><label for="id_username" class="form-input-label">Contact Number <i class="form-optional-tag">(Optional)</i></label><br>
        {{ form.area_code }}{{ form.telephone }}<br><p>{{ form.telephone.errors }}{{ form.area_code.errors }}
        <button type="submit" class="form-button">Update Job Listing</button>
    </form>
</div>
{% endblock %}

templates/editlistingportal.html
{% extends "base.html" %}

{% block content %}

    <h1 class="pageheader">Edit Your Job Listings</h1>

    <div class="editjoblistingportal">
    <p class="jobcounter">You have <b>{{ joblistings.count }}</b> listings available</p>
    {% if joblistings %}
            {% for joblisting in joblistings %}
                 <div class="edit-listings-item">
                   <a>
                   <ul>
                   <li class="listing-title">{{ joblisting.job_title }} - {{ joblisting.business_name }}</li>
                   <li>Region: {{ joblisting.get_business_address_suburb_display }}</li>
                   <li>Pay Rate: ${{ joblisting.pay_rate }}</li>
                   <li>Contact Method: {{ joblisting.contact_method }}</li>
                   <div class="listings-item-delete"><a href="{% url 'deletelistingconfirm' joblisting.pk %}">Delete Listing</a></div>
                   <div class="listings-item-delete"><a href="{% url 'editlisting' joblisting.pk %}">Edit Listing</a></div>
                   </ul>
                   </a>
                 </div>
            {% endfor %}

    {% else %}
        <p>Oops! You have no editable Job Listings.</p>
    {% endif %}
    </div>
{% endblock %}

templates/editprofile.html
{% extends "base.html" %}

{% block content %}

    <p>Test!</p>
    {{ form.as_p }}

{% endblock %}

templates/feature_notimplemented.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <img src="{% static 'images/feature.png' %}" class="feature" />
    <h1 class="pageheader">Sorry, we are still in the process of implementing this feature!</h1>

{% endblock %}

templates/listing.html
{% extends "base.html" %}

{% block content %}
<div class="listing-wrapper">
    <div class="listing-content">
        <div class="listing-left-column">
        <p class="listing-details-title">Job Details</p>
        <p class="listing-details-bold">Job Title:</p><p class="listing-details-info">{{ joblistings.job_title|capfirst }}</p>
        <p class="listing-details-bold">Employment Type:</p><p class="listing-details-info">{{ joblistings.get_employment_type_display }}</p>
        <p class="listing-details-bold">Pay Rate:</p><p class="listing-details-info">${{ joblistings.pay_rate }}</p>
        <p class="listing-details-bold">Business Region:</p><p class="listing-details-info">{{ joblistings.get_business_address_region_display }}</p>
        <p class="listing-details-bold">Business Suburb:</p><p class="listing-details-info">{{ joblistings.get_business_address_suburb_display|capfirst }}</p>
        <p class="listing-details-bold">Business Industry:</p><p class="listing-details-info">{{ joblistings.get_business_industry_display }}</p>
        <p class="listing-details-bold">Email:</p><p class="listing-details-info">
            {% if joblistings.email != '' %}
                {{ joblistings.email|capfirst }}
            {% else %}
                Not Provided
            {% endif %}
        </p>
        <p class="listing-details-bold">Contact Number:</p><p class="listing-details-info">
            {% if joblistings.telephone != '' %}
                ({{ joblistings.get_area_code_display }}) {{ joblistings.telephone }}
            {% else %}
                Not Provided
            {% endif %}
        </p>
        {% if joblistings.email != '' %}
            <button type="submit" class="listing-details-button">
            <a href="mailto:{{ joblistings.email }}?Subject={{ joblistings.job_title }}%20-%20Application%20-%20Opus Jobs" class="listing-email-link">Email Employer</a></button>
        {% endif %}

        </div>
        <div class="listing-right-column">
        <h1 class="listing-title-secondary">{{ joblistings.job_title|capfirst }}</h1>
        <p class="listing-job-description">{{ joblistings.job_description }}</p>
            <div class="listing-application">
                <h1 class="listing-details-title">How To Apply?</h1>
                <ul class="listing-application-bullets">
                    <li>Each employer will have provided either a contact number, a email or both in the job details to the left.</li>
                    <li>You can contact them via any of the methods provided, whichever one suits you best.</li>
                    <li>Just make sure when you do, that you let them know Opus sent you!</li>
                </ul>
                <div class="listing-application-contact">
                    <div><p class="listing-application-bold">Email:</p><p class="listing-application-info">
                        {% if joblistings.email != '' %}
                            {{ joblistings.email|capfirst }}
                        {% else %}
                            Not Provided
                        {% endif %}
                    </p></div>
                    <div><p class="listing-application-bold">Contact Number:</p><p class="listing-application-info">
                        {% if joblistings.telephone != '' %}
                            ({{ joblistings.get_area_code_display }}) {{ joblistings.telephone }}
                        {% else %}
                            Not Provided
                        {% endif %}
                    </p></div>
                </div>
            </div>
        </div>
    </div>
</div>
    <p class="view-counter-title">Page Views</p>
    <div class="view-counter">
        <p>{{ joblistings.listing_view_counter|stringformat:"05d" }}</p>
    </div>
    <div class="ad-alert">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Listings Banner -->
        <ins class="adsbygoogle" style="display:inline-block;width:728px;height:90px" data-ad-client="ca-pub-9407013200292589" data-ad-slot="7535806952"></ins>
        <script>(adsbygoogle = window.adsbygoogle || []).push({});</script>
    </div>
<script>
function myFunction() {
    alert("Sorry! This employer has only provided a contact number.");
}
</script>

{% endblock %}

templates/permission_denied.html
{% extends "base.html" %}
{% load static %}

{% block content %}

    <img src="{% static 'images/permission_denied.png' %}" class="feature" />
    <h1 class="pageheader">Woah there! We think you might have got somewhere you shouldn't have. </h1>

{% endblock %}